Feature/signin signup back connection
DiegoAvmor/uady-spa-project pull request #14
Opened 2022-05-16 14:42 UTC by HerCerM

### Demo

https://user-images.githubusercontent.com/42811720/168723752-24282587-bfb6-49d4-9243-c973fe2182ce.mp4

### Pending tasks for the navbar

- Redirect **admin** user on sign in to the "View users" view (this is his _Home_ view)
- Setup correct URLs for the **admin-only** views, i.e. "View users" and "Sign up user"

2022-05-16 17:54 UTC, DiegoAvmor requested changes

2022-05-16 17:54 UTC, DiegoAvmor commented on src/app/components/ui/navbar/navbar.component.html
> +    ></app-navbar-link>
No tenemos contemplado este boton y vista en lo que definimos. Lo que tenemos en maquetado es solo la vista de los usuarios.

2022-05-16 17:54 UTC, DiegoAvmor commented on src/app/components/ui/navbar/navbar.component.html
> +      [allowedUserRoles]="['regular']"
Como no tenemos maquetado y definido la funcionalidad de la vista 'Sign Up User' para no dejar la barra de navegacion del admin tan vacio podriamos permitir que el Home tambien aparezca para el admin.

2022-05-17 03:35 UTC, HerCerM commented on src/app/components/ui/navbar/navbar.component.html
> +    ></app-navbar-link>
Eliminé este link de navegación

2022-05-17 03:35 UTC, HerCerM commented on src/app/components/ui/navbar/navbar.component.html
> +      [allowedUserRoles]="['regular']"
De acuerdo, agregué al usuario admin en la vista de Home

2022-05-17 03:50 UTC, DiegoAvmor approved these changes

2022-05-17 03:50 UTC, merged